sudo: true

language: bash

services:
  - docker

env:
  global:
    - DOCKERHUB="user/endpoint"

jobs:
  include:
    - stage: BuildImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -t ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB}:latest
