os: linux

language: shell

branches:
  only:
    - universal-git #replace variables, omit brackets

services:
  - docker

env:
  global:
    - DOCKERHUB="linuxserver/mods" #don't modify
    - BASEIMAGE="universal" #replace
    - MODNAME="git" #replace

jobs:
  include:
    - stage: PR-BuildImage
      if: (type IN (pull_request))
      script:
        # Build image
        - docker build --no-cache -t ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}-${TRAVIS_COMMIT} .
    - stage: BuildImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -t ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}-${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}-${TRAVIS_COMMIT} ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}-${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}
